<?php

return [
    'categorie' => [
        "gaming"=>[
            'id' => 1,
            'url' => 'gaming',
            'nom' => 'Gaming',
            'categorie_parent' => null,
            'description' => null,
        ],
        "minecraft"=>[
            'id' => 2,
            'url' => 'minecraft',
            'nom' => 'Minecraft',
            'categorie_parent' => 1,
            'description' => null,
        ],
        "fivem"=>[
            'id' => 3,
            'url' => 'fivem',
            'nom' => 'Fivem',
            'categorie_parent' => 1,
            'description' => null,
        ],
    ],
    'product' => [
        'minecraft' => [
            'title' => 'Serveur Minecraft',
            'url' => 'minecraft',
            'titre_head' => 'Serveur Minecraft',
            'description_head' => 'Serveur Minecraft de qualité, avec un support de qualité.',
            '30j' => true,
            'product_list' => [
                'FreeCloud' => [
                    'title' => 'Essaie Gratuit',
                    'price_format' => '0.00',
                    'price_cents' => '000',
                    'price_currency' => '€',
                    'type' => 'essaie',
                    'period' => 'mois',
                    'price_type' => 'mois',
                    'description' => 'Pour tester nos offres obtener un essaie gratuit de 48h.',
                    'features' => [
                        '1' => 'CPU 2x 2.4 GHz',
                        '2' => 'RAM 4GB DDR4',
                        '3' => 'Stockage SSD 32GB',
                        '4' => 'Base de données MySQL 1',
                        '5' => 'Trafic illimité',
                        '6' => 'Protection Anti-DDoS',
                        '7' => 'Sauvegardes quotidiennes',
                        '8' => 'Support 24/7',
                    ],
                    'url' => 'game-hosting/minecraft/FreeCloud',
                    'url_message' => 'Commandez votre essaie gratuit',
                    'highlight' => true,
                ],
                'CreeperCloud' => [
                    'title' => 'CreeperCloud',
                    'price_format' => '2.99',
                    'price_cents' => '299',
                    'price_currency' => '€',
                    'period' => 'mois',
                    'price_type' => 'mois',
                    'description' => 'Pour les petits projets',
                    'features' => [
                        '1' => 'CPU 2x 2.4 GHz',
                        '2' => 'RAM 4GB DDR4',
                        '3' => 'Stockage SSD 32GB',
                        '4' => 'Base de données MySQL 1',
                        '5' => 'Trafic illimité',
                        '6' => 'Protection Anti-DDoS',
                        '7' => 'Sauvegardes quotidiennes',
                        '8' => 'Support 24/7',
                    ],
                    'url' => 'game-hosting/minecraft/CreeperCloud',
                    'url_message' => 'Commandez votre serveur Minecraft',
                    'highlight' => false,
                ],
                'ZombieCloud' => [
                    'title' => 'ZombieCloud',
                    'price_format' => '4.99',
                    'price_cents' => '499',
                    'price_currency' => '€',
                    'period' => 'mois',
                    'price_type' => 'mois',
                    'description' => 'Pour les petits projets',
                    'features' => [
                        '1' => 'CPU 2x 2.4 GHz',
                        '2' => 'RAM 6GB DDR4',
                        '3' => 'Stockage SSD 64GB',
                        '4' => 'Base de données MySQL 3',
                        '5' => 'Trafic illimité',
                        '6' => 'Protection Anti-DDoS',
                        '7' => 'Sauvegardes quotidiennes',
                        '8' => 'Support 24/7',
                    ],
                    'url' => 'game-hosting/minecraft/ZombieCloud',
                    'url_message' => 'Commandez votre serveur Minecraft',
                    'highlight' => false,
                ],
                'BlazeCloud' => [
                    'title' => 'BlazeCloud',
                    'price_format' => '9.99',
                    'price_cents' => '999',
                    'price_currency' => '€',
                    'period' => 'mois',
                    'price_type' => 'mois',
                    'description' => 'Pour les petits projets',
                    'features' => [
                        '1' => 'CPU 2x 2.4 GHz',
                        '2' => 'RAM 12GB DDR4',
                        '3' => 'Stockage SSD 90GB',
                        '4' => 'Base de données MySQL 5',
                        '5' => 'Trafic illimité',
                        '6' => 'Protection Anti-DDoS',
                        '7' => 'Sauvegardes quotidiennes',
                        '8' => 'Support 24/7',
                    ],
                    'url' => 'game-hosting/minecraft/BlazeCloud',
                    'url_message' => 'Commandez votre serveur Minecraft',
                    'highlight' => false,
                ],
                'SpiderCloud' => [
                    'title' => 'SpiderCloud',
                    'price_format' => '19.99',
                    'price_cents' => '1999',
                    'price_currency' => '€',
                    'period' => 'mois',
                    'price_type' => 'mois',
                    'description' => 'Pour les petits projets',
                    'features' => [
                        '1' => 'CPU 2x 2.4 GHz',
                        '2' => 'RAM 24GB DDR4',
                        '3' => 'Stockage SSD 128GB',
                        '4' => 'Base de données MySQL 10',
                        '5' => 'Trafic illimité',
                        '6' => 'Protection Anti-DDoS',
                        '7' => 'Sauvegardes quotidiennes',
                        '8' => 'Support 24/7',
                    ],
                    'url' => 'game-hosting/minecraft/SpiderCloud',
                    'url_message' => 'Commandez votre serveur Minecraft',
                    'highlight' => false,
                ],
                'EnderCloud' => [
                    'title' => 'EnderCloud',
                    'price_format' => '24.90',
                    'price_cents' => '2490',
                    'price_currency' => '€',
                    'period' => 'mois',
                    'price_type' => 'mois',
                    'description' => 'Pour les petits projets',
                    'features' => [
                        '1' => 'CPU 2x 2.4 GHz',
                        '2' => 'RAM 32GB DDR4',
                        '3' => 'Stockage SSD 190GB',
                        '4' => 'Base de données MySQL 20',
                        '5' => 'Trafic illimité',
                        '6' => 'Protection Anti-DDoS',
                        '7' => 'Sauvegardes quotidiennes',
                        '8' => 'Support 24/7',
                    ],
                    'url' => 'game-hosting/minecraft/EnderCloud',
                    'url_message' => 'Commandez votre serveur Minecraft',
                    'highlight' => false,
                ],
            ],
        ],
        'fivem' => [
            'title' => 'Serveur FiveM',
            'url' => 'fivem',
            'titre_head' => 'Serveur FiveM',
            'description_head' => 'Serveur FiveM de qualité, avec un support de qualité.',
            '30j' => true,
            'product_list' => [
                'fiveFree' => [
                    'title' => 'Essaie gratuit',
                    'price_format' => '0.00',
                    'price_cents' => '000',
                    'price_currency' => '€',
                    'type' => 'essaie',
                    'period' => 'mois',
                    'price_type' => 'mois',
                    'description' => 'Pour tester notre offre, obtenir un essaie gratuit de 48h.',
                    'features' => [
                        '1' => 'CPU 1x 2.4 GHz',
                        '2' => 'RAM 2GB DDR4',
                        '3' => 'Stockage SSD 20GB',
                        '4' => 'Base de données MySQL 1',
                        '5' => 'Trafic illimité',
                        '6' => 'Protection Anti-DDoS',
                        '7' => 'Activation instantanée',
                        '8' => 'Sauvegardes quotidiennes',
                        '9' => 'Support 24/7',
                        '10' => 'Activation Clé Argentum',
                    ],
                    'url' => 'game-hosting/fivem/FiveFree',
                    'url_message' => 'Commandez votre essaie gratuit Fivem',
                    'highlight' => true,
                ],
                'fiveDev' => [
                    'title' => 'FiveDev',
                    'price_format' => '0.90',
                    'price_cents' => '090',
                    'price_currency' => '€',
                    'period' => 'mois',
                    'price_type' => 'mois',
                    'description' => 'Pour le dev',
                    'features' => [
                        '1' => 'CPU 1x 2.4 GHz',
                        '2' => 'RAM 2GB DDR4',
                        '3' => 'Stockage SSD 20GB',
                        '4' => 'Base de données MySQL 1',
                        '5' => 'Trafic illimité',
                        '6' => 'Protection Anti-DDoS',
                        '7' => 'Activation instantanée',
                        '8' => 'Sauvegardes quotidiennes',
                        '9' => 'Support 24/7',
                        '10' => 'Activation Clé Argentum',
                    ],
                    'url' => 'game-hosting/fivem/FiveDev',
                    'url_message' => 'Commandez votre serveur FiveM',
                    'highlight' => false,
                ],
                'fiveSmart' => [
                    'title' => 'FiveSmart',
                    'price_format' => '1.99',
                    'price_cents' => '199',
                    'price_currency' => '€',
                    'period' => 'mois',
                    'price_type' => 'mois',
                    'description' => 'Pour les petits projets',
                    'features' => [
                        '1' => 'CPU 1x 2.4 GHz',
                        '2' => 'RAM 5GB DDR4',
                        '3' => 'Stockage SSD 65GB',
                        '4' => 'Base de données MySQL 4',
                        '5' => 'Trafic illimité',
                        '6' => 'Protection Anti-DDoS',
                        '7' => 'Activation instantanée',
                        '8' => 'Sauvegardes quotidiennes',
                        '9' => 'Support 24/7',
                        '10' => 'Activation Clé Argentum',
                    ],
                    'url' => 'game-hosting/fivem/FiveSmart',
                    'url_message' => 'Commandez votre serveur FiveM',
                    'highlight' => false,
                ],
                'FivePlus' => [
                    'title' => 'FivePlus',
                    'price_format' => '3.99',
                    'price_cents' => '399',
                    'price_currency' => '€',
                    'period' => 'mois',
                    'price_type' => 'mois',
                    'description' => 'Pour les petits projets',
                    'features' => [
                        '1' => 'CPU 1x 2.4 GHz',
                        '2' => 'RAM 12GB DDR4',
                        '3' => 'Stockage SSD 90GB',
                        '4' => 'Base de données MySQL 5',
                        '5' => 'Trafic illimité',
                        '6' => 'Protection Anti-DDoS',
                        '7' => 'Activation instantanée',
                        '8' => 'Sauvegardes quotidiennes',
                        '9' => 'Support 24/7',
                        '10' => 'Activation Clé Argentum',
                    ],
                    'url' => 'game-hosting/fivem/FivePro',
                    'url_message' => 'Commandez votre serveur FiveM',
                    'highlight' => false,
                ],
                'FivePro' => [
                    'title' => 'FivePro',
                    'price_format' => '19.99',
                    'price_cents' => '1999',
                    'price_currency' => '€',
                    'period' => 'mois',
                    'price_type' => 'mois',
                    'description' => 'Pour les petits projets',
                    'features' => [
                        '1' => 'CPU 1x 2.4 GHz',
                        '2' => 'RAM 24GB DDR4',
                        '3' => 'Stockage SSD 130GB',
                        '4' => 'Base de données MySQL 10',
                        '5' => 'Trafic illimité',
                        '6' => 'Protection Anti-DDoS',
                        '7' => 'Activation instantanée',
                        '8' => 'Sauvegardes quotidiennes',
                        '9' => 'Support 24/7',
                        '10' => 'Activation Clé Argentum',
                    ],
                    'url' => 'game-hosting/fivem/FivePro',
                    'url_message' => 'Commandez votre serveur FiveM',
                    'highlight' => false,
                ],
            ],
        ],
    ],
];
